global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vehicle-service'
    static_configs:
      - targets: ['vehicle-service:8081']

  - job_name: 'tracking-service'
    static_configs:
      - targets: ['tracking-service:8082']

  - job_name: 'dashboard-service'
    static_configs:
      - targets: ['dashboard-service:8084']

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:8083']

  - job_name: 'service-registry'
    static_configs:
      - targets: ['service-registry:8761']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
